export const CAPABILITIES = {
  DASHBOARD_VIEW: "dashboard:view",
  CASES_VIEW: "cases:view",
  CASES_VIEW_ALL: "cases:view_all",
  CASES_VIEW_DIVISION: "cases:view_division",
  CASES_CREATE: "cases:create",
  CASES_EDIT: "cases:edit",
  CASES_EDIT_DIVISION: "cases:edit_division",
  CASES_DELETE: "cases:delete",
  CASES_ASSIGN: "cases:assign",
  CASES_ASSIGN_DIVISION: "cases:assign_division",
  CASES_PROPOSE_EDIT: "cases:propose_edit",
  CASES_APPROVE_EDITS: "cases:approve_edits",
  CASES_APPROVE_DIVISION: "cases:approve_division",
  ROSTER_VIEW: "roster:view",
  ROSTER_VIEW_DIVISION: "roster:view_division",
  ROSTER_MANAGE: "roster:manage",
  ROSTER_MANAGE_DIVISION: "roster:manage_division",
  BULLETIN_VIEW: "bulletin:view",
  ANNOUNCEMENTS_MANAGE: "announcements:manage",
  REQUESTS_VIEW: "requests:view",
  ACTIVITY_VIEW: "activity:view",
  SETTINGS_MANAGE: "settings:manage",
} as const;

export type Capability = (typeof CAPABILITIES)[keyof typeof CAPABILITIES];
